#
# Ingress
#
ingress:
  enabled: true
  annotations: 
    kubernetes.io/tls-acme: "true"
    # traefik.ingress.kubernetes.io/router.middlewares: "security-oauth2-proxy@kubernetescrd"
    cert-manager.io/cluster-issuer: "letsencrypt"
  
  # define a custom ingress class Name, like "traefik" or "nginx"
  className: "traefik"
  hosts:
    - host: n8n.cagou.ovh
      paths: 
        - /
  tls:
    - hosts:
        - n8n.cagou.ovh
      secretName: n8n-tls

# the main (n8n) application related configuration + Kubernetes specific settings
# The config: {} dictionary is converted to environmental variables in the ConfigMap.
main:
  # See https://docs.n8n.io/hosting/configuration/environment-variables/ for all values.
  config: 

    N8N_HOST:
      "n8n.cagou.ovh"
    N8N_PROTOCOL:
      "https"
    WEBHOOK_URL:
      "https://n8n.cagou.ovh/"

      
  #
  persistence:
    # If true, use a Persistent Volume Claim, If false, use emptyDir
    enabled: true
    # what type volume, possible options are [existing, emptyDir, dynamic] dynamic for Dynamic Volume Provisioning, existing for using an existing Claim
    type: dynamic


  resources: 
  # We usually recommend not specifying default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 200m
    memory: 512Mi

  nodeSelector:
    kubernetes.io/arch: arm64

