kubetail:
  dashboard:
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: "security-oauth2-proxy@kubernetescrd"
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: "letsencrypt"
      tls:
        - secretName: kubetail-tls
          hosts:
            - kubetail.orarm.cagou.ovh
      # not in initial values.yaml      
      rules:
        - host: kubetail.orarm.cagou.ovh
          http:
            paths:
            - path: /
              pathType: Prefix
      className: traefik