ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt"
  hosts:
    - host: datalab.cagou.ovh
  tls:
     - secretName: onyxia-tls
       hosts:
         - datalab.cagou.ovh