server:
  ingress:
    enabled: true
    hostname: argocd.cagou.ovh
    ingressClassName: traefik
    tls: true
    annotations:
      traefik.ingress.kubernetes.io/max-body-size: "128Mi"
  certificate:
    enabled: true
    issuer: 
      kind: ClusterIssuer
      name: letsencrypt
    domain: argocd.cagou.ovh
  certificateSecret:
    enabled: true

global:
  domain: argocd.cagou.ovh

configs:
  params:
    server.insecure: true
  cm:
    kustomize.buildOptions: "--enable-helm"