node:
  resources:
    livenessProbe:
      limits:
        memory: 80Mi # 100Mi
      requests:
        cpu: 10m
        memory: 20Mi
    nodeDriverRegistrar:
      limits:
        memory: 80Mi # 100Mi
      requests:
        cpu: 10m
        memory: 20Mi
    nfs:
      limits:
        memory: 150Mi # 300Mi a kustomize sur controlplane ?
      requests:
        cpu: 10m
        memory: 20Mi


