---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-cd-registry-secret
  namespace: boten-anna
spec:
  encryptedData:
    .dockerconfigjson: AgB/M0CalruAMz8tQD6gbeYgOi3NTR261HjAulrfuo3ZwyIGnO7Y2X1wRj/0KDfjW+JSBjLGCPnsekvFbn550Mn4vRaeWPk3IPL3UF4qv7T7+4RXRLzCwZozZqOolZk+GJYyLIYzFrRVr3hl3qdT4cyNJO5UvuwU9+PC4M8eIkoG/U/s6oV5fBRinraow8+A4Yr+uAR8uA5GSLJGWXXAuyU8wT+SUlZAHdYxrnPV/xENMDAJsF/xH+r06m61YTmyBVHYIUcsCixyL8Bc1olPZubK/AcPSqXKPuuH5B+o5DETtMiSr5R5FWy/MQb6pj0KPLYOc/nh5GU8KN42k2BxvZRcp3Hd0KonNpvaH09KXPZXNHP2CWY1NJuaSqE4GQGaeiJhB4mzFh/IgeqdiqDNNyiMkM7dTrXdDGZ6xnQZXUIxErNpHFGo7lhT/gcu9mHoMp4Vj+gF0pTWSkIQcvnNNj1UZbP5QptW2FC7HbyUjq1rrJhnKdw6MJSMN3+7XuSulFisCZq3UX4RpO7oj4ZIwQnylCy/pGW8vcuZx/8cSEL7W2oDoKyUR5XnIpLbneHRMBXznG1NBaaW1e0leuYst/Sd8QvDMoH5s6GI4qIEkQoZUhrj5dVnVqAcbvRTPnHloYFrlFspNOILk1nvxbhn0vjGAzvGqFJE6yuhuW6kujZ19MUX4E2VyNqJgAfrDSUEWTeDwA8cGNM46+vPoZVobh9j8iKcEv2YhjPDAHCX0ttB6Booi/SqW9TjaXS0AOtyBNz3IP5YR3h82nR2MjiMdyaF9GHy2fVHRoI2P2/LdyKxOWvXVQT4cZ0gfGTWzEcCBgzDregsBPlhiXy27PWqf8eQfLKDX8gGgaiahWlot7ZLud60APS0yfULGiZP8BvQFKhpMjPo0cTKAjC4yNbY3nAPIv4QYfAKPyRBum54ytwZRCWkEo+ucXYB5qA=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-cd-registry-secret
      namespace: boten-anna
    type: kubernetes.io/dockerconfigjson
