---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAq4aZCCYW0eNJuhdIKyLCKvZdo0wz7AiaxYgm7J+VOogIIlNEKpITAMWR2yVB3ZeYg1q+qxB1R27XuWfzYPhx1O/vsN7NvjtkwsLTxA+vt5yptu2NbmqrFq2x8Fa5q75Swjmx6fUWQdp9MUgzBLHSXxE9aCKEX06vZA+EJG2DB/hlNo5YJbmrMQV/meTEwsznaZgPJVilPYqFdN8ZSNcZuxjDjcUK6ioQTldDtQFunmN8oQ8RV7Qg+hV0a84bFVwfTdDphB2A2c7Bxl0lmzqkIMx0tSaVhYcYzNzCywMMkl6m+oWkI7G0RPldpci404UMZVOSylSuIOcBZ+F7/nj7WON3cpt6xF8cRm23bjbqQDIFPmA0ERxYHiuKYPK+3d7OqKaEW30VgvF6qfCKzWOXhemlG437Ha6Y+nxLCu2/bW26mQqA55931Y9rRDNSM06Lo1FddYkHeFzj56qnmHjzxhJwsT7lopSHB3P8CdCHmPX6BADPi8hG9xNpxqgST3rg5m+DvkRH3R7ndDcTDDKw0wsMDQFgqwJFqKgGo91BqdoXRiYod0gpPKFu+970Myeao1j73lbWXOUvlR1ZtTVCfevrPtp+WlcZCBob22ET2v3U232mIEJVhI8KZShZF1JD+5xExcg0a3jxAst/o0WcuIEeYQ56k4RJzTq/Xv9toUTYApZ1NSs2WIpmFlnGSQ1QbVIBJZE3e0hLSlg1DOLMCQw==
    client_secret: AgCZL5Iz8SksDyc6GamRYFKJs84Kk/rD5HrPsTFj5/L8e9OewO2kPtu2SUcz7SqNePe/eQhZnMtKq2JI8F5iV62du9n1dk/rYKyx4L4acySWYsdugaMbzPaX22w8HcAXgIBHkmOTnMnZzY/x24IqH4m8tV3FXfNeVaUJ/dIpxgboNneXBoFPNcfJQY9F56D5NlEJL9TPIdX6IIMxIeSyPXbM+N7uHHz6bf0RycjhEs+wFXn8sDELKZa2iWLltVlRnAIb3cBD2mdOTFg24mHgEI5Le/C4QgK7jqgZ8JtvdV4OWmwZiRk0Am77+PXlgu/BGv3xVPojSvifPJOm4tGPSz61PO+zeYlckaJHP2KBIfc6hTAhhGfh471ORuR+IR1FmP+y/GZlCpKKcbJoiw7cuvGuPWIWw8IWeN0tBgXBPSRUWfYLJMu8VCZkUBmR8/6HC4hzSCkYg4Lut2h9OqYhm2FoZd7oz6jjgmhOhm5zLGcejkCY5m/1Q2hoFt6O7JZj8feBk1k4ehGXU9/U9/UYgv6MBwwpnnaqvBKB0oqwN3jL8BkKrd/aI7GNyN+sNbCo4yiAEpIOVN5Hq90Ax617ol8sdGoc+/7XCZ7fdJoPFHfAuDmBOvzUvcFY/8YJ6vHnSAT9JK9+o92oWD6lkdIRY8IUdTNHcyo1tASXnbysAq+IB3F747Kzgngrea3WfNa4B9SP0qfXQecxZW0705Mu80UVOmwOpZ2JeQV1yA6gyRo2WeV/yRj8WNzB6LvMW/WSj+FObsNINbU3ppg4oWPrEwIs
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
