primary: # Configuration pour le pod primaire/unique
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - arm64 
auth:
  # Nom de la base de données à créer pour Harbor
  database: harbor_db
  username: harbor_user
  existingSecret: harbor-pg-secret

  secretKeys:
    userPasswordKey: pg-user-password
    adminPasswordKey: pg-admin-password

primary:
  persistence:
    enabled: true
    size: 1Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 150m     
    limits:
      memory: 1024Mi 
      cpu: 500m    
