apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airbyte
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://airbytehq.github.io/helm-charts/
    targetRevision: 1.6.0-alpha-b62b3bec781
    chart: airbyte
    helm:
      valueFiles:
      - $values/apps/tools/airbyte/values.yaml
  - repoURL: 'https://github.com/abugeia/orarm.git'
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true