apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onyxia
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://github.com/coder/code-server.git
    path: ci/helm-chart/
    targetRevision: HEAD
    helm:
      valueFiles:
      - $values/apps/dev/code-server/values.yaml
  - repoURL: 'https://github.com/abugeia/orarm.git'
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: datalab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
