apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abugeia/orarm.git
    targetRevision: main
    path: config
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
