apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubetail
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://kubetail-org.github.io/helm-charts/
    targetRevision: kubetail-0.9.10
    chart: kubetail
    helm:
      valueFiles:
      - $values/observability/kubetail/values.yaml
  - repoURL: 'https://github.com/abugeia/orarm.git'
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true