apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: 8gears.container-registry.com/library
    targetRevision: 1.0.7
    chart: n8n
    helm:
      valueFiles:
      - $values/apps/tools/n8n/values.yaml
  - repoURL: 'https://github.com/abugeia/orarm.git'
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true