apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onyxia
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://InseeFrLab.github.io/onyxia
    targetRevision: 10.9.9
    chart: onyxia
    helm:
      valueFiles:
      - $values/apps/datalab/onyxia/values.yaml
  - repoURL: 'https://github.com/abugeia/orarm.git'
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: datalab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
