apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://helm.releases.hashicorp.com"
    targetRevision: 0.28.0  # Vérifie la dernière version
    chart: "vault"
    helm:
      values: |
        server:
          ingress:
            enabled: true
            ingressClassName: "traefik"
            hosts:
              - host: vault.orarm.cagou.ovh  # Change avec ton domaine
                paths:
                  - "/"
            tls:
              - secretName: vault-tls
                hosts:
                  - vault.orarm.cagou.ovh
          dev:
            enabled: false
          standalone:
            enabled: true
          ha:
            enabled: false
          dataStorage:
            enabled: false  # Désactive le stockage persistant
          injector:
            enabled: true     # Active l'injecteur de secrets pour Kubernetes
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true