
name: Copy SSH Key to Instance

on:
  workflow_dispatch:
    inputs:
      public_key:
        required: true  
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PUB_KEY: ${{ github.event.inputs.public_key }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy SSH public key to instance
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "mkdir -p ~/.ssh && echo '$SSH_PUB_KEY' >> ~/.ssh/authorized_keys"


