---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-creds
  namespace: boten-anna
spec:
  encryptedData:
    .dockerconfigjson: AgAj82JFmJI2N5P7+pd3zwd14uLHI3ktv3kdFzy+lyS3gWAyC8Xyv0b66XR1PBXa8UihlgITytYq7o3mbxVbaKh3x/lRTzG3ZNYJVmVTgjLQDFVDQ67VBLgIAalq1xbyNs7Lke8aXBEbTocUQwhNgEhFpkmA3Mx0JcW9qIi4BdPumVJ/TmqjFUuh5SANnfTGL4xljqJCEq8i2tuZTn2Y5AJnIf4IuRYe+innPEjM9XC+RHvPRm40eKL4fBVVQGtqH3kRYpJoNZPVnqz4RN7xVnDs/i8Gyp9xtBiQTjJ+rc+rqjSewNRU/1jytgauAYZn4M9q4Q5EcU1NmZ1UCZ2MS0M008iYe7nfESRLCPfHgcwyU1hHd60oFVHVsDnlNIwoObeSPAdRf8HhFKYjM3HpO8x3Oqo52GfgGODo6f+1n38jPEXgf7Zb2BcdMP1mxCpVgZhhaY+KdaLCGVIOEjTIUQSxoO3Bz2+VNS+gWIji+gp2QM96kfBuKJ6E4nqjA+gDasylayBuqpBwHmvic8cAlw5R78KSWrdBbLEYCbW/+j/V9Rf0ADCUGZTjXi+yyB7Goq1jgwAUztcgcuG8/9CA2AeliQFM6hlz8sjQ0Gs1YW9q87C5E2dEnD8wtmbGS1ZlkeTzlZSI5+ZtjIFtlJ4WC9jKxs20BumxCgnz1wn06iWMfn2POKprdWX+Rfs+pNu15M3YevWBfn656JYRgfB7WAmEp0JNxQM9qtEGqF8hkvvuroFfB8HevcYSEuzEzlcmNxUoy/QoFbAnFczlmuZwmZMzEObLZWvmyn7b0uLquvRuUMavWtPFzRbiCjdnja5qfRUGmzL/+9jawyBGf8C7CcnRAr3Ww8KMsYW6tbi4uJTtXKhEqRK/+AdO6ZDsyMtFX4QG8xFeK56oyrqFEATiqhk6kcmVEp6e35xIc2gVEqhbRMO2Jsd5+twb/VE=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-creds
      namespace: boten-anna
    type: kubernetes.io/dockerconfigjson
